version: "3"
services:
  # auth
  databaseAuth:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # ports:
    #   - 3306:3306
    volumes:
      - ./upravljanje_korisnickim_nalozima/init:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/mysql
    networks:
      - auth_network
  adminerAuth:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - auth_network
  authentication:
    image: authentication
    ports: 
      - 5000:5000
    environment:
      - PRODUCTION="PRODUCTION"
    networks:
      - auth_network

  # store
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # ports:
    #   - 3306:3306
    volumes:
      - ./upravljanje_prodavnicom/init:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/mysql
    networks:
      - store_network
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - store_network
  owner:
    image: owner
    ports: 
      - 5001:5001
    environment:
      - PRODUCTION="PRODUCTION"
    networks:
      - store_network
  customer:
    image: customer
    ports: 
      - 5002:5002
    environment:
      - PRODUCTION="PRODUCTION"
    networks:
      - store_network
    depends_on:
      ganache:
        condition: service_healthy
  courier:
    image: courier
    ports: 
      - 5003:5003
    environment:
      - PRODUCTION="PRODUCTION"
    networks:
      - store_network
    depends_on:
      ganache:
        condition: service_healthy

  # spark
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8090:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - store_network
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8091:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - store_network
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8092:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - store_network
  sparkapp:
    image: myspark1
    environment:
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=sparkapp
      - DATABASE_IP=database
    ports:
      - 5004:5004
    networks:
      - store_network

  # blockchain
  ganache:
    image: trufflesuite/ganache-cli
    ports:
     - 8545:8545
    networks:
      - store_network
    healthcheck:
      test: ["CMD", "nc", "-z", "ganache", "8545"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  auth_network:
  store_network: